### ISSUE TITLE
Specify config file when runing the container.

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/simulator#3]
Something like this would be cool:

```
make run config=config_file.json
```

This will also avoid merge conflicts when pulling remote changes after editing `parameters.json`. The `parameters.json` file should be copied and modified, the container should then be run with the modified config file.

**Comment by sphemakh** [comment]
Fixed in  6410948

**Comment by gijzelaerr** [comment]
6410948 looks quite empty?

**Comment by sphemakh** [comment]
Oops, its 5ad18fa15b5a0d4c0812d91e522feef4cd3fd521
